### ISSUE TITLE
Warlock Class: Proper Number of Soul Shards Not Created When Using Shadowburn + Drain Soul

### ISSUE THREAD

**Issue by Afkplayer1** [VanillaPlusTeam/bug-tracker#101] opened 2023-06-10 21:02 UTC
**Describe Your Issue**
When my Warlock kills a mob that grants experience with the Drain Soul ability and the Shadowburn debuff is present on the target, I only get one Soul Shard.

**Steps To Reproduce**

1. Be a Warlock with the Drain Soul ability trained and Shadowburn talent learned
2. Lower the health of a mob
3. Cast Shadowburn (make sure it doesn't kill the mob)
4. Cast Drain Soul once the mob drops below 20% health (make sure the mob dies within the 2 second cast)
5. Observe that only one (1) soul shard is created, instead of two (2)

Item: https://www.wowhead.com/classic/item=6265/soul-shard Spell: https://www.wowhead.com/classic/spell=23464/create-soul-shard

**Expected Behavior**
This sequence of events should award two (2) Soul Shards--one from Shadowburn debuff being present during the kill and another from killing with/during Drain Soul.

**Comment by Trymv1** [comment] 2023-06-11 08:41
This was apparently a Vanilla thing, the code is the same for both spells so you only get one.

**Comment by Fuku2222** [comment] 2023-06-22 13:49
Yeah this is normal - you can't get 2 shards from one mob. It's either shadowburn + drain for burst, or pick one if you need shard(s). 
Not a bug, close this 'issue' (non-issue)

**Comment by Fuku2222** [comment] 2023-07-01 14:52
It should be noted if you are using abilities on different targets you will ofc gain 2 shards (presuming targets die in time)

**Closed as completed** 2024-03-21 17:17 UTC
